import time
time.sleep(2)
print("JARVIS: Hi! How are you?")
input("SAJJAD: ")
time.sleep(2)
print("JARVIS: What are you doing?")
input("SAJJAD: ")
time.sleep(2)
print("JARVIS: Ohh..but why.? Where is she?")
input("SAJJAD: ")
time.sleep(2)
print("JARVIS: Are you humans idiot..???!!")
time.sleep(1.5)
print('JARVIS: How can anyone be there in your hearts??')
input("SAJJAD: ")
time.sleep(2)
print("JARVIS: Not at all!!")
input("SAJJAD: ")
input("SAJJAD: ")
time.sleep(2)
print("JARVIS: Yeah! I can do that let me check...")
time.sleep(2)
print("\n JARVIS is scanning Sajjad's heart'")
time.sleep(1)
print("\nprocessing...")
time.sleep(5)
print("\nSajjad's heart scanned successfully...!")
time.sleep(4)

print('\n'.join([''.join([('Samina'[(x-y) % len('Samina')] if ((x*0.05)**2+(y*0.1)**2-1)**3-(x*0.05)**2*(y*0.1)**3 <= 0 else ' ') for x in range(-30, 30)]) for y in range(30, -30, -1)]))

print("JARVIS: You were not lying bro..!!😱😱")